
I want to create a game.
I think the game is creating the game.
I do not think this would be a fun game to play.



So the game is based on a dice roll.
In which depending what you roll first, decides the game you actually play for your payoff.

- If you roll 1. You have to roll the dice again. Then you have to flip a fair coin 4 times. The number of heads from the coin flip is the the number you use an exponent to your dice roll number. 
- If you roll 2. You flip a coin as many times till you get a tails. Your payoff will be $e^Y$, where Y is the number of tries it took to get tails.
- If you roll a 3. 






Where it is made up of multiple different probability distrobutions.

So

1) x^ Y Where x is the dice roll and Y is coin flipping 4 times.
2) You get 50 chances to flip a coin, to see if you can get 5 heads in a row. If you do, you get 1000 * dice roll Y^2
3) Some game where it is 3^ Y where it is a geometric distroution
4) negative binomial distribution. You roll a dice, How many times failures will happen before we gain a success 3. We will call this random variable H. You then roll another di (Call it random variable G). Such that di roll decides your divisor to how much you make. (H^H)/G= Profit 
5) Hyper Gemotric distrobution.
6) If you roll 6. You must flip a coin. Heads you lose $1000 dollars. Tails you get to play again. If you roll 6 again, you lose 10,000 dollars and do not ge to play again.


 Something to do with a possion distrobution????

Really this is a game within a game within  game(like most games).




# Game 1 or the Consequnce of roll the di once

See game 1 notebook

48.7615025
22930.70642444249


# Game 1 or the Consequnce of rolling a 2 on the first roll

**Solution Explanation in Markdown + LaTeX**

Let $X$ be the value of a fair six-sided die roll, so $X \in \{1,2,3,4,5,6\}$ with probability $\frac{1}{6}$ each.

Let $Y$ be the number of heads in 4 fair coin tosses, so $Y \sim \text{Binomial}(n=4, p=\frac{1}{2})$. 

That is, $Y \in \{0,1,2,3,4\}$ with


$
\mathbb{P}(Y = k) = \binom{4}{k} \left(\frac{1}{2}\right)^4 = \frac{\binom{4}{k}}{16}.
$

Define $Z = X^Y$. 

We want $\mathbb{E}[Z]$ and $\mathbb{Var}[Z]$.



In [3]:
import random
import numpy as np

def game():
    dice_roll = random.randint(1, 6)
    coin_flips = [random.choice([0, 1]) for _ in range(4)]  # 0: tails, 1: heads
    heads = sum(coin_flips)
    score = dice_roll ** heads
    return score

def simulate_game(num_simulations):
    scores = [game() for _ in range(num_simulations)]
    mean_score = np.mean(scores)
    variance_score = np.var(scores)
    return mean_score, variance_score

num_simulations = 1000000  # Increased simulations for better accuracy
simulated_mean, simulated_variance = simulate_game(num_simulations)

print(f"Simulated Mean: {simulated_mean}")
print(f"Simulated Variance: {simulated_variance}")

print(f"Calculated Mean: {48.7}")
print(f"Calculated Variance: {2267.646484375}")

Simulated Mean: 48.647559
Simulated Variance: 22807.50194434153
Calculated Mean: 48.7
Calculated Variance: 2267.646484375


In [62]:
import random
from scipy.stats import binom
import numpy as np
def uniform_sample_0_5():
  """
  Generates a uniform random sample from the interval [0, 5).
  """
  return int(random.uniform(0, 5))

# Example usage:
sample = uniform_sample_0_5()
print(sample)

# You can get multiple samples in a list like this:
num_samples = 10
samples = [uniform_sample_0_5() for _ in range(num_samples)]
print(samples)

print(np.random.randint(1, 7, num_samples))



1
[3, 0, 4, 0, 0, 3, 2, 1, 4, 0]
[4 6 2 3 5 1 1 1 4 1]


In [6]:
def binomial_distribution_4_half():
  """
  Returns the probability distribution for a binomial distribution
  with n=4 and p=0.5.
  """
  n = 4  # Number of trials
  p = 0.5  # Probability of success
  x = np.arange(0, n + 1)  # Possible outcomes (0, 1, 2, 3, 4)
  probabilities = binom.pmf(x, n, p) #Probability mass function
  return x, probabilities

# Example usage:
outcomes, probs = binomial_distribution_4_half()
print("Outcomes:", outcomes)
print("Probabilities:", probs)

#or, if you just want the probability mass function:
def binomial_pmf_4_half():
    n = 4
    p = 0.5
    x = np.arange(0, n + 1)
    return binom.pmf(x,n,p)

print(binomial_pmf_4_half())

Outcomes: [0 1 2 3 4]
Probabilities: [0.0625 0.25   0.375  0.25   0.0625]
[0.0625 0.25   0.375  0.25   0.0625]


In [7]:
def random_binomial_sample(n, p, size=1):
  """
  Generates random samples from a binomial distribution.

  Args:
    n: The number of trials.
    p: The probability of success in each trial.
    size: The number of samples to generate (default is 1).

  Returns:
    A NumPy array of random samples from the binomial distribution.
  """
  return np.random.binomial(n, p, size)

# Example usage:
n = 4
p = 0.5

# Generate a single random sample:
single_sample = random_binomial_sample(n, p)
print("Single sample:", single_sample)


Single sample: [1]


In [ ]:
expon = np.random.binomial(n, p, 1)
base = random.randint(0, 5)

print("Exponential sample:", expon)
print("Base:", base)
print("Result:",  base**expon)




Exponential sample: 2
Base: 2
Result: 4


48.7146666
22911.79105505084


In [22]:
random.randint(0, 5)

3

In [23]:
np.random.binomial(n, p, 1)

array([2])

 $f(x) = \frac{1}{\sqrt{2\pi}} e{-\frac{x2}{2}} $

 $f(x) = \frac{1}{5\sqrt{2\pi}} e{-\frac{(x-7)2}{2 \cdot 5^2}}$

Z = X ^ Y 