

First I need to find the charastric equation
$\begin{bmatrix}
3 & -2 & 4 \\
-2 & 6 & 2 \\
4 & 2 & 4
\end{bmatrix}$


$\begin{bmatrix}
3- \lambda & -2 & 4 \\
-2 & 6 - \lambda & 2 \\
4 & 2  & 4 - \lambda
\end{bmatrix}$


We want to get atleast one zero here, to save some computation. So row row 1 plus row 3

$\begin{bmatrix}
3- \lambda & -2 & 4 \\
-2 & 6 - \lambda & 2 \\
7- \lambda & 0  & 8 - \lambda
\end{bmatrix}$

Now determinent


$\begin{bmatrix}
3 - \lambda & -2 & 4 \\
-2 & 6 - \lambda & 2 \\
7- \lambda & 0  & 8 - \lambda
\end{bmatrix}$



$(3- \lambda) (48 -14 \lambda + \lambda ^2) \\
+
-2 ( ( 16 + 2 \lambda) - 14 + 2 \lambda) \\
+
4(-2*0 - (6- \lambda)(7- \lambda) )
$ 


$ (3- \lambda) (48 -14 \lambda + \lambda ^2) \\
+
60 - 8 \lambda \\
+
4(- (\lambda ^2  - 13 \lambda + 42))
$ 



$ (3- \lambda) (48 -14 \lambda + \lambda ^2) \\
+
60 - 8 \lambda \\
-4\lambda ^2  + 52 \lambda - 168 \\
$ 




$ (3- \lambda) (48 -14 \lambda + \lambda ^2) \\
-4\lambda ^2  + 46 \lambda - 108
$ 


$  36  - 44 \lambda +  + 13 \lambda^2 - \lambda ^3  $ 

$  36  - (44 +  + 13 \lambda - \lambda ^2) \lambda  $ 


$( \lambda - 2)^2 (\lambda - 9) $ 

#### Now find the eigenvectors

#### For $\lambda =2$

$\begin{bmatrix}
3 - \lambda & -2 & 4 \\
-2 & 6 - \lambda & 2 \\
4 & 2  & 4 - \lambda
\end{bmatrix}$


$\begin{bmatrix}
1 & -2 & 4 \\
-2 & 4 & 2 \\
4 & 2  & 2
\end{bmatrix}$


$\begin{bmatrix}
1 & -2 & 4 \\
0 & 0 & 10 \\
4 & 2  & 2
\end{bmatrix}$



$\begin{bmatrix}
1 & -2 & 4 \\
0 & 0 & 1 \\
0 & 1  & 0
\end{bmatrix}$



$\begin{bmatrix}
1 & 0 & 0 \\
0 & 0 & 1 \\
0 & 1  & 0
\end{bmatrix}$


Oh crap I did something wrong....
This would mean the vector is the zero vector.
But that cannot be.

This is too time consuming to try to find the damn little error I made.

Characteristic Polynomial:
λ**3 - 13*λ**2 + 30*λ + 84
PurePoly(λ**3 - 13*λ**2 + 30*λ + 84, λ, domain='ZZ')
Characteristic polynomial:
   3       2            
- λ  + 13⋅λ  - 30⋅λ - 84

Eigenvalues:
[7, 3 - sqrt(21), 3 + sqrt(21)]


$(\lambda + 2)(\lambda - 6) (\lambda -7)$

### Find eigenvector of $\lambda = -2$

$\begin{bmatrix}
5 & -2 & 4 \\
-2 & 8 & 2 \\
4 & 2 & 6
\end{bmatrix}$


divide row 2 and 3 by 2
$\begin{bmatrix}
5 & -2 & 4 \\
-1 & 4 & 1 \\
2 & 1 & 3     
\end{bmatrix}$

add row2 * 5 to row 1
add row2 *2 to row 3

$\begin{bmatrix}
0 & 18 & 9 \\
-1 & 4 & 1 \\
0 & 5 & 4
\end{bmatrix}$


mulitple row3 by $\frac{2}{5}$ for easy operation in next step

$\begin{bmatrix}
0 & 2 & 1 \\
-1 & 0 & -1 \\
0 & \frac{5*2}{5} & \frac{8}{5}
\end{bmatrix}$

subtract row1 to row3

$\begin{bmatrix}
0 & 2 & 1 \\
-1 & 0 & -1 \\
0 & 0 & \frac{3}{5}
\end{bmatrix}$

This seems like a matrix that the solution will be the zero vector which cannot be right!

$\begin{bmatrix}
0 & 2 & 1 \\
-1 & 0 & -1 \\
0 & 0 & \frac{3}{5}
\end{bmatrix}$

In [5]:
Lambda2 = sp.Matrix([
    [5, -2, 4],
    [-2, 8, 2],
    [4, 2, 6]
])
sp.Matrix(Lambda2).rref()

(Matrix([
 [1, 0, 0],
 [0, 1, 0],
 [0, 0, 1]]),
 (0, 1, 2))

In [13]:
import sympy as sp

λ = sp.Symbol('λ')

A = sp.Matrix([
    [3, -2, 4],
    [-2, 6, 2],
    [4, 2, 4]
])

char_poly = A.charpoly(λ)


print("Characteristic Polynomial:")
print(char_poly.as_expr())

λ = sp.Symbol('λ')
poly = λ**3 - 13*λ**2 + 30*λ + 84

# Factor the polynomial
factored = sp.factor(char_poly)
print(factored)



# Define the variable λ
λ = sp.symbols('λ')

# Create the characteristic polynomial: det(A - λI)
char_poly = (A - λ * sp.eye(3)).det()

# Expand the polynomial (optional but nice for viewing)
char_poly = sp.expand(char_poly)
print("Characteristic polynomial:")
sp.pprint(char_poly)

# Solve for eigenvalues (roots of the characteristic polynomial)
eigenvalues = sp.solve(char_poly, λ)
print("\nEigenvalues:")
print(eigenvalues)


Characteristic Polynomial:
λ**3 - 13*λ**2 + 30*λ + 84
PurePoly(λ**3 - 13*λ**2 + 30*λ + 84, λ, domain='ZZ')
Characteristic polynomial:
   3       2            
- λ  + 13⋅λ  - 30⋅λ - 84

Eigenvalues:
[7, 3 - sqrt(21), 3 + sqrt(21)]


In [17]:
vecctors = []
for val in eigenvalues:
    print(f"\nEigenvalue λ = {val}:")
    eig_matrix = A - val * sp.eye(3)
    null_space = eig_matrix.nullspace()

    if null_space:
        for i, vec in enumerate(null_space):
            print(f"Eigenvector {i + 1}:")
            sp.pprint(vec)
            vecctors.append(vec)
    else:
        print("No eigenvector found (should not happen).")


Eigenvalue λ = 7:
Eigenvector 1:
⎡-1/2⎤
⎢    ⎥
⎢ 1  ⎥
⎢    ⎥
⎣ 0  ⎦

Eigenvalue λ = 3 - sqrt(21):
Eigenvector 1:
⎡-(16⋅√21 + 84) ⎤
⎢───────────────⎥
⎢  63 + 17⋅√21  ⎥
⎢               ⎥
⎢ -(8 + 2⋅√21)  ⎥
⎢ ───────────── ⎥
⎢  3⋅√21 + 17   ⎥
⎢               ⎥
⎣       1       ⎦

Eigenvalue λ = 3 + sqrt(21):
Eigenvector 1:
⎡-(-84 + 16⋅√21) ⎤
⎢────────────────⎥
⎢  -63 + 17⋅√21  ⎥
⎢                ⎥
⎢ -(-8 + 2⋅√21)  ⎥
⎢ ────────────── ⎥
⎢  -17 + 3⋅√21   ⎥
⎢                ⎥
⎣       1        ⎦


In [18]:
def gram_schmidt(vectors):
    orthonormal_basis = []
    
    for v in vectors:
        w = v.copy()
        for u in orthonormal_basis:
            proj = (v.dot(u)) * u
            w -= proj
        w = sp.simplify(w / w.norm())
        orthonormal_basis.append(w)

    return orthonormal_basis


orthonormal = gram_schmidt(vecctors)

for i, vec in enumerate(orthonormal, 1):
    print(f"u{i} = {vec}")


u1 = Matrix([[-sqrt(5)/5], [2*sqrt(5)/5], [0]])
u2 = Matrix([[(-29*sqrt(21) - 131)/sqrt(15592*sqrt(21) + 71463)], [(-29*sqrt(21) - 131)/(2*sqrt(15592*sqrt(21) + 71463))], [(51*sqrt(21) + 239)/(2*sqrt(15592*sqrt(21) + 71463))]])
u3 = Matrix([[2500*(-8316 + 1819*sqrt(21))/(sqrt(15592*sqrt(21) + 71463)*(-3935673*sqrt(5) + 858857*sqrt(105)))], [1250*(-8316 + 1819*sqrt(21))/(sqrt(15592*sqrt(21) + 71463)*(-3935673*sqrt(5) + 858857*sqrt(105)))], [625*(29883 - 6497*sqrt(21))/(sqrt(15592*sqrt(21) + 71463)*(-3935673*sqrt(5) + 858857*sqrt(105)))]])


In [19]:
import sympy as sp

# Define the matrix
A = sp.Matrix([
    [3, -2, 4],
    [-2, 6, 2],
    [4, 2, 4]
])

# Step 1: Find eigenvalues and eigenvectors
eigen_data = A.eigenvects()

# Step 2: Flatten all eigenvectors and apply Gram-Schmidt
vecs = []
for eigenval, _, vect_list in eigen_data:
    vecs.extend(vect_list)

# Step 3: Gram-Schmidt Orthonormalization
def gram_schmidt(vectors):
    ortho = []
    for v in vectors:
        for u in ortho:
            v -= v.project(u)
        ortho.append(v)
    return [v / v.norm() for v in ortho]

ortho_vecs = gram_schmidt(vecs)

# Step 4: Construct matrix P from orthonormal eigenvectors
P = sp.Matrix.hstack(*ortho_vecs)

# Step 5: Compute diagonal matrix D
D = P.T * A * P

# Show results
sp.pprint(D)

⎡                                                                              ↪
⎢                                                                              ↪
⎢                                                                              ↪
⎢                                                                              ↪
⎢                                                                              ↪
⎢                                                                              ↪
⎢                                                                              ↪
⎢                                                                              ↪
⎢                                                                              ↪
⎢                                                                              ↪
⎢                                                                              ↪
⎢                                                                              ↪
⎢                           

In [20]:
import numpy as np

# Step 1: Define the matrix
A = np.array([
    [3, -2, 4],
    [-2, 6, 2],
    [4, 2, 4]
], dtype=float)

# Step 2: Get eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eigh(A)

# Step 3: Normalize eigenvectors (they're already orthonormal from eigh, but we’ll ensure it)
Q = eigenvectors
Q = Q / np.linalg.norm(Q, axis=0)

# Step 4: Create diagonal matrix D
D = np.dot(np.dot(Q.T, A), Q)

# Print results
print("Orthonormal Matrix P (Q):")
print(np.round(Q, 4))

print("\nDiagonal Matrix D:")
print(np.round(D, 4))


Orthonormal Matrix P (Q):
[[-0.6981  0.4472  0.5592]
 [-0.349  -0.8944  0.2796]
 [ 0.6252 -0.      0.7805]]

Diagonal Matrix D:
[[-1.5826 -0.     -0.    ]
 [-0.      7.     -0.    ]
 [-0.     -0.      7.5826]]
